### ISSUE TITLE
NaN RMSE - what could be the issue?

### ISSUE THREAD

**Issue by vsumaria** [CompPhysVienna/n2p2#100]
**The question**
I am trying to generate an interatomic potential for an alloyed system using AIMD data. I am following the training procedure as discussed in the documentation, but ending up with an NaN RMSE for both energy and forces. What exactly could be the reason? 

**What did you already try?**
I am thinking it has to do something with the calculated symmetry functions, but I cannot figure out the exact problem. Any help would be great.

**Comment by singraber** [comment]
I'm sorry but that's just not enough information for me to give you any hint where the problem could lie.. You should at least provide some information whether NaNs appear only at the training stage or even earlier when using ``nnp-scaling``. Do you see NaNs in ``scaling.data``?

**Comment by vsumaria** [comment]
No, the scaling data has no NAN values. The first iteration of training itself gives all the RMSE errors as NaN.

**Comment by singraber** [comment]
Have you managed to get a successful training run? I assume so because of the issue #104... I noticed in your files that you have many symmetry functions that have a very limited "range", i.e. the minimum and maximum value in `scaling.data` are very close together. This may be problematic since symmetry functions are rescaled before fed into the NN.. when the "range" is very small this means a large scaling factor and hence noise gets also blown up. You may consider removing those symmetry function definitions from `input.nn` and see if your training performs equally good (or maybe even better/faster). There is also a convenient tool for this purpuose: [nnp-prune](https://compphysvienna.github.io/n2p2/tools/nnp-prune.html). Please have a look at the [Prune before training](https://compphysvienna.github.io/n2p2/tools/nnp-prune.html#prune-before-training) section. A quick trial with your data showed that 64 symmetry functions could be removed.

**Comment by vsumaria** [comment]
#104 was actually for a different system, where we might have potentially identified a bug. But Iill try and use nnp-prune to see the effect. I agree that the range could be an issue. Hopefully this can fix the issue, will update the results as it does.

**Comment by vsumaria** [comment]
This was the perfect solution. Thanks, it fixed it. Closing the issue.
