### ISSUE TITLE
Pynnp

### ISSUE THREAD

**Issue by mozhde** [CompPhysVienna/n2p2#117]
**The question**
I am planning to use the "Pynnp" library. To do so, I started with running the examples in "Pynnp/prediction"

I did a test; I ran the exact python example (the same input.nn, input.data, etc) and got the Reference and NNP energies as follow:

Energy (Ref) :  -1225.22167939
Energy (NNP) :  226.6527928086986
then I did the same calculation using "nnp-predict" and got

Energy (Ref): -1.22522168E+03
Energy(NNP) : -1.22409045E+03

As you can see the prediction using these two methods are very different; and I couldn't figure it out why. I was wondering if you could help me with it?

Thanks

**Comment by singraber** [comment]
Hello and sorry for the late reply..

I suspect that you are using the `example-verbose.py` script, which was written before the data set normalization feature was added to the C++ code. Hence, a few calls need to be added to the script and in order to be able to do that I have to add stuff to the C++/Python wrapper. It will not be a lot of work, I will write a fix in the next days...

**Comment by singraber** [comment]
I just fixed this here: https://github.com/CompPhysVienna/n2p2/commit/6cc948bb052718b6d4225d62efb33b9d3abdef78, it should work now in the current `master` branch.
