### ISSUE TITLE
Symmetry functions with different cutoffs

### ISSUE THREAD

**Issue by Matheus-Novoa** [CompPhysVienna/n2p2#153]
I'm testing the Ethylbenzene_SCAN potential, present in examples/potentials folder. I notice that, in the symmetry functions section, each symmetry function line has a different cutoff value. 

My question is which cutoff value i have to use in "pair_coeff" in lammps.

**Comment by Matheus-Novoa** [comment]
I inserted the largest value of symnetry functions cutoff and worked.

I tested the etilbenzene_SCAN potential example with the lammps interface, but i got extrapolation warnings.

I guess this problem is out of scope of this issue, then i will open another one.

Thanks for your help.

**Comment by philippmisof** [comment]
The extrapolation warning means that the potential is used for configurations which are beyond the range of the data set used for training. Thus you can't use the potential for your current MD run since the potential wasn't trained for your use case (e.g. not for the temperature in your MD). Unfortunately I wasn't involved in the development of this potential so I don't know any more details.
But I agree, if you want to discuss this topic further it would be best to open a new issue for that.

You're welcome
