### ISSUE TITLE
Does libnnptrain require MKL?

### ISSUE THREAD

**Issue by dkumarrav** [CompPhysVienna/n2p2#26]
Hi,

We are trying to compile n2p2 on Ubuntu 16.04. libnnp and libnnpif compiled successfully. But while trying to compile libnnptrain, we get the following error:

mpic++ -O3 -march=native -std=c++11 -fopenmp -Wno-long-long -g -pedantic-errors -Wall -Wextra -I./ -I../../include/ -I/usr/include/gsl/ -I/usr/include/eigen3/ -DEIGEN_DONT_PARALLELIZE -DEIGEN_USE_BLAS -o ../../build/static/Training.o -c Training.cpp
In file included from /usr/include/eigen3/Eigen/Core:74:0,
                 from KalmanFilter.h:22,
                 from KalmanFilter.cpp:17:
/usr/include/eigen3/Eigen/src/Core/util/MKL_support.h:57:21: fatal error: mkl.h: No such file or directory
compilation terminated.
makefile:109: recipe for target '../../build/static/KalmanFilter.o' failed
make[1]: *** [../../build/static/KalmanFilter.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/include/eigen3/Eigen/Core:74:0,
                 from KalmanFilter.h:22,
                 from Training.cpp:19:
/usr/include/eigen3/Eigen/src/Core/util/MKL_support.h:57:21: fatal error: mkl.h: No such file or directory
compilation terminated.
makefile:109: recipe for target '../../build/static/Training.o' failed
make[1]: *** [../../build/static/Training.o] Error 1
make[1]: Leaving directory '/media/data_drive/Dharam/n2p2-master/src/libnnptrain'
makefile:242: recipe for target 'libnnptrain' failed
make: *** [libnnptrain] Error 2

Is MKL required for compiling libnnptrain? Could you please help us resolve this issue?

Thank you!!

**Comment by singraber** [comment]
Hello!

No, Intel MKL is not required, although some BLAS library is needed by the GSL (see https://www.gnu.org/software/gsl/doc/html/usage.html#linking-programs-with-the-library). In addition, if in `makefile.gnu` the option `PROJECT_OPTIONS+= -DEIGEN_USE_BLAS` is active (which is the default) also the Eigen library requires an external BLAS library. Unfortunately Ubuntu 16.04 comes with a rather old Eigen package (3.3~beta1) which allowed only MKL as external BLAS dependency (see this thread: https://forum.kde.org/viewtopic.php?f=74&t=110509). So I think there are two options you can try to solve the compilation problem:

1. **Either install a newer version of Eigen:**
This is very easy since Eigen is a header-only library. Just download the library from here: http://eigen.tuxfamily.org and unpack it in some directory. Then provide the path to Eigen in `makefile.gnu` in line 9 in the variable `PROJECT_EIGEN`.

2. **Or don't compile Eigen with external BLAS dependency:**
This is even simpler, just comment out `PROJECT_OPTIONS+= -DEIGEN_USE_BLAS` in line 45 in `makefile.gnu`. I'm not entirely sure whether this option will influence training speed though.

Hope this helps, please report back if problems persist!

**Comment by dkumarrav** [comment]
Thank you!
 both the solution worked
