### ISSUE TITLE
Support of multiple pair styles via hybrid/overlay in lammps interface

### ISSUE THREAD

**Issue by cschran** [CompPhysVienna/n2p2#29]
I am trying to setup a lammps simulation adding a NNP for some atoms/elements to a LJ interaction with other elements (using the hybrid/overlay pair style). Unfortunately, I wasn't able to make this work, because the n2p2 lammps interface seems to not support multiple pair styles at the moment. As far as I can tell, the n2p2 interface uses always all atoms from lammps.

E.g. the quip interface does solve this problem by mapping lammps atom types to quip elements via the pair_coeff (see also [documentation](https://lammps.sandia.gov/doc/pair_quip.html)):
`pair_coeff      * * quip.xml "QUIP initialization string" atomic_numbers`

It would be great, if support for multiple pair styles could be added to the lammps interface.

Thanks!
Christoph

**Comment by singraber** [comment]
That's a good idea.. although I was always aware that a `pair_hybrid` setup could be an interesting option for LAMMPS users, I never had an actual use case to try it out. Since you may have started working on this.. do you have a minimal working example which you can send me (i.e. a LAMMPS script, an input configuration, ...)? If you have already tried to run a hybrid simulation, where does it fail?

Best,
Andi

**Comment by cschran** [comment]
Hi Andi,

I'll setup a minimal working example with published NNP parameters and post it here.

The simulations that I tried so far failed with the following error: `ERROR: Number of LAMMPS atom types (3) and NNP elements (2) does not match.`
This happens because 2 elements are described by the NNP and a third element type is supposed to be coupled to those atoms via LJ interactions. The interface however passes all elements to n2p2.

Thanks and all the best,
Christoph

**Comment by cschran** [comment]
Attached is a MWE of a water hexamer coupled to a single argon atom via a LJ potential.
The water NNP is from this [repo](https://github.com/BingqingCheng/ab-initio-thermodynamics-of-water).

[lammps_hybrid_mwe.zip](https://github.com/CompPhysVienna/n2p2/files/4135554/lammps_hybrid_mwe.zip)

**Comment by singraber** [comment]
Ok great, thanks! I will try to have a look at this tomorrow.. next week I will be on vacation, so if I can't find a quick fix tomorrow then I will have to ask you for a little patience until the week after, sorry..

**Comment by singraber** [comment]
Looking good so far (see #30).. there will be a keyword "emap" which will allow to provide a list of all atom types used by the NNP, all others will be ignored. Maybe I can finish this later today...

**Comment by cschran** [comment]
very nice! thanks a lot for the super fast support! I'll give it a try as soon it's finished.

**Comment by singraber** [comment]
So I think this is working fine now.. I tested it with the MWE you gave me in the following way: First I set up two versions of the MWE (see [lammps_hybrid_comparison.zip](https://github.com/CompPhysVienna/n2p2/files/4186927/lammps_hybrid_comparison.zip)):

* **only-h2o**: Contains only the 6 water molecules (18 atoms), removed the Ar atom and the interaction definition in the LAMMPS script.
* **extra-type**: Contains 6 water molecules + the Ar atom ( 19 atoms total) and effectively turned off the interaction of the Ar atom with the water molecules:
   ```
   pair_coeff     2 3 lj/cut 0.00000 4.56789
   ```
   Also, I applied the initial velocity command only to the water molecules
   ```
   group water type 1 2
   velocity water create ${initTemp} ${velSeed}
   ```

Moreover, in both versions I disabled the thermostat and used the NVE ensemble instead. Under these circumstances, the two trajectories should be identical because the extra Ar atom has no actual interaction with the H and O atoms. Luckily, this is exactly what I am observing :-).

So I think you can proceed from here and do some further testing with the interaction turned on. Maybe you could place the Ar atom further away so that it interacts only with one H or O atom, dump the forces and distances and manually check the additional energy and force contributions (just a suggestion).

**NOTE**: I will not yet merge #30 into the main repo as I want to add some CI tests first. So in the meantime, please be sure to check out the feature branch for testing: https://github.com/singraber/n2p2/tree/fix_lammps_hybrid.

**USAGE**: There is now an additional keyword `emap` for the LAMMPS `pair_style nnp` which allows you to specify the "LAMMPS atom type to n2p2 element" mapping. The syntax is pretty self-explanatory: it is just a string with a comma-separated list of `type:element` mappings, e.g.
```
pair_style nnp emap "1:H,2:O" ...
```
maps type 1 and 2 to H and O atoms, respectively. Any type that is not mentioned in this list is completely ignored by the NNP. The keyword `emap` is mandatory in a "hybrid" setup with "extra" atom types in the simulation which are not handled by the NNP. In a "non-hybrid" situation it is optional and allows to explicitly map types to elements. If it is omitted the default behavior is restored, i.e. LAMMPS atom types are assumed to be in order of ascending atomic number.

Hope this helps, please report any problems, bugs, etc...

**Comment by cschran** [comment]
Thanks for your efforts! I'll checkout the branch and do some testing tomorrow and report back.

**Comment by cschran** [comment]
Hi Andi,

it's working nicely with the new branch. I ran some tests and can't find any issues up to now. Thanks for the great work!

Best, Christoph

**Comment by singraber** [comment]
Hey Christoph,

great, glad I could help! Yes, I will leave it open until the tests are done and the PR is merged.

All the best,
Andi

**Comment by singraber** [comment]
#30 is now merged, I am closing this..

**Comment by cschran** [comment]
thanks again for your effort! It's quite a nice feature to have. Cheers, Christoph
