### ISSUE TITLE
Cabana version of n2p2

### ISSUE THREAD

**Issue by streeve** [CompPhysVienna/n2p2#32]
We have modified a portion of the n2p2 code to work with our library, Cabana, and proxy application, CabanaMD ((https://github.com/ECP-copa/CabanaMD). Cabana (https://github.com/ECP-copa/Cabana) is a particle library built on Kokkos (https://github.com/kokkos/kokkos/) for performance portability

@singraber has suggested we move it to this repository and I completely agree

Here is my initial plan:
- [x] Complete existing work for better interface to the n2p2 kernels that require Cabana data structures (ECP-copa/CabanaMD#37)
- [x] Move code to this repository, within `src/libnnpif-cabana` initially (see below)
- [x] Create child classes (e.g. `ModeCabana`) and override functions as necessary (there are currently implementations for `Mode`, `Element`, `CutoffFunction`)
- [x] Simplify existing setup code by calling base methods and copying to Kokkos/Cabana data structures
- [x] Add optional Kokkos/Cabana dependencies
- [x] Add documentation on building and running with Kokkos/Cabana
- [x] Remove from current repository (`master` and `OnNode` branch) 

Thank you,

**Comment by singraber** [comment]
Hey,

and sorry for commenting this so late (our everyday life here changed drastically due to Corona..). That is excellent news, sounds great! I am looking forward to trying it out.

I have one minor suggestion: I originally intended to keep only the core functionality within the `libnnp` directory. This way compiling the basic parts of the package will be possible without many dependencies. Interfaces to external software would then go to the `libnnpif` ("if" for interface) directory. Then again, I am beginning to question my original idea to put ALL interfaces to `libnnpif`.. it makes no sense that a user who wants to build the LAMMPS interface also needs to fulfill all requirements for the future CabanaMD link. So, I am adding to the task list something for me to think about:

- [ ]  Find a clever way to organize interfaces with external software.

All the best,
Andi

**Comment by streeve** [comment]
My only new thought in finally opening the PR to close this is that perhaps `libnnpif` could be renamed `libnnpif-lammps` (or both LAMMPS and Cabana interfaces named something new)

**Comment by singraber** [comment]
I finally merged #49 with some minor changes:

* Renamed the source files (i.e. `ElementCabana` instead of `Element_Cabana`)
* Added documentation (see [here](https://compphysvienna.github.io/n2p2/Interfaces/if_cabanamd.html)), I included also a link to your paper on arXiv.

My plan is to create a new release version (via Github releases, which will automatically create an archive and a DOI on Zenodo) as soon as you finish work on CabanaMD with NNP (https://github.com/ECP-copa/CabanaMD/pull/61, https://github.com/ECP-copa/CabanaMD/issues/37). This way it may be easier for users and also for CI tests.. do you think this is a good idea or do you suggest something different? Also, I will take version numbers more serious in the future. I am thinking of integrating a CabanaMD build also in Travis to make sure I don't break things without noticing.

Let me know if you need some changes or want me to do some testing!

**Comment by streeve** [comment]
Great! I merged and removed all n2p2 code from CabanaMD. 

I agree; tagged versions are best. I will update my CI once the n2p2 tag is available. I assume you would also prefer a release of CabanaMD? I have one more update in functionality before I would like to do one, but that should be done soon.

At the very least any failures due to interface should show up in CabanaMD for now

**Comment by streeve** [comment]
Maybe best to close this and open a similar CI/tag issue here?

**Comment by singraber** [comment]
Yes, I will add some basic testing when a tag is available, no need to hurry. Created an issue: #65. Closing this one, thanks again for your efforts!
