### ISSUE TITLE
Specifing cutoff radius (rc)

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#39]
Hi.
I need to apply a different value for the cutoff radius (rc) than the default (12 Bohr). I've been wondering how it would be possible to change it. I've got an idea from the Cu2S example to specify it using "_r_c_" keyword in the SYMMETRY FUNCTIONS section (https://github.com/CompPhysVienna/n2p2/blob/master/examples/input.nn.recommended), i. e. "r_c   = _value_" . However, even with this keyword, it is still using the default value. Maybe it has to be specified in a different way. Any help would be greatly appropriated. Thanks.

**Comment by singraber** [comment]
The lines with `rc = ...` in the `input.nn.recommended` file are ignored by n2p2 tools (all lines starting with `#` are treated as comments). The actual cutoff radius is set for each symmetry function separately, it is usually the last parameter but to be sure always check the parameter definition, i.e. click on the links in the table [here](https://compphysvienna.github.io/n2p2/Topics/keywords.html#symfunction-short).

Since writing symmetry function definitions by hand is cumbersome, @flobuch added a little tool to simplify this process (see #15). The comments you mentioned https://github.com/CompPhysVienna/n2p2/blob/c7b4407317fdf9bfcfd5a20f805f5e8948083243/examples/input.nn.recommended#L108-L115
were added by the [`sfparamgen.py`](https://github.com/flobuch/n2p2/blob/symfunc_paramgen/tools/python/symfunc_paramgen/src/sfparamgen.py) tool (see [docs](https://github.com/flobuch/n2p2/blob/symfunc_paramgen/tools/python/symfunc_paramgen/examples/example.ipynb)) when creating the symmetry function lines. See also the updated [documentation page](https://compphysvienna.github.io/n2p2/Topics/training.html#step-2-nn-and-symmetry-function-setup)

**Comment by moabe75** [comment]
Many thanks Andreas. Now, I understand what's going on.
I've tried the "sfparamgen.py" tool. It is really helpful for generating the symmetry function parameters.
