### ISSUE TITLE
Linking error while making LAMMPS with USER-NNP

### ISSUE THREAD

**Issue by hghcomphys** [CompPhysVienna/n2p2#40]
Hi Andreas, 

I am trying to make a LAMMPS with USER-NNP, but getting a compilation error. I have the previous version of NNP (v1.0.0) which is working just fine on the same machine. but with the recent version, I confront this error.

Steps that I perform are as follow:
- I used the most updated version of the lammps and n2p2
- on nnp src directory I use: $make COMP=intel all  (also tried with gnu compiler but getting another error)
- make a link to nnp in lammps lib directory
- on lammps src directory I use: $make yes-user-nnp && make serial

OS: ubuntu 18.04, icc  18.0.2 
part of log file and the error I confront when I compiled the lammps:

/usr/bin/ld: ../../lib/nnp/lib/libnnpif.a(InterfaceLammps.o): relocation R_X86_64_32 against `_ZN17_INTERNAL3d953dc2St8__ioinitE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(Structure.o): relocation R_X86_64_32 against `_ZN17_INTERNALa5f037e3St8__ioinitE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(Atom.o): relocation R_X86_64_32 against `.rodata.str1.32' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(Log.o): relocation R_X86_64_32 against `_ZN17_INTERNAL5d0a61afSt8__ioinitE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(ElementMap.o): relocation R_X86_64_32 against symbol `_ZN3nnp10ElementMap13knownElementsB5cxx11E' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(Mode.o): relocation R_X86_64_32 against `.rodata.str1.4' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(utility.o): relocation R_X86_64_32S against symbol `_ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(NeuralNetwork.o): relocation R_X86_64_32 against `.rodata.str1.4' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(Element.o): relocation R_X86_64_32 against `_ZN17_INTERNAL96d6fd14St8__ioinitE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionAngularNarrow.o): relocation R_X86_64_32 against symbol `_ZTIN3nnp29SymmetryFunctionAngularNarrowE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionStatistics.o): relocation R_X86_64_32 against `_ZN17_INTERNAL6dc4d014St19piecewise_constructE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionGroupAngularNarrow.o): relocation R_X86_64_32 against symbol `_ZTIN3nnp34SymmetryFunctionGroupAngularNarrowE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionGroup.o): relocation R_X86_64_32 against symbol `_ZN3nnp21SymmetryFunctionGroup11printFormatB5cxx11E' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(CutoffFunction.o): relocation R_X86_64_32S against symbol `_ZNK3nnp14CutoffFunction5fHARDEd' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(Settings.o): relocation R_X86_64_32 against symbol `_ZN3nnp8Settings13knownKeywordsB5cxx11E' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionWeightedRadial.o): relocation R_X86_64_32 against symbol `_ZTIN3nnp30SymmetryFunctionWeightedRadialE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionRadial.o): relocation R_X86_64_32 against symbol `_ZTIN3nnp22SymmetryFunctionRadialE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionGroupWeightedRadial.o): relocation R_X86_64_32 against symbol `_ZTIN3nnp35SymmetryFunctionGroupWeightedRadialE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionWeightedAngular.o): relocation R_X86_64_32 against symbol `_ZTIN3nnp31SymmetryFunctionWeightedAngularE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionAngularWide.o): relocation R_X86_64_32 against symbol `_ZTIN3nnp27SymmetryFunctionAngularWideE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionGroupWeightedAngular.o): relocation R_X86_64_32 against symbol `_ZTIN3nnp36SymmetryFunctionGroupWeightedAngularE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionGroupAngularWide.o): relocation R_X86_64_32 against symbol `_ZTIN3nnp32SymmetryFunctionGroupAngularWideE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunctionGroupRadial.o): relocation R_X86_64_32 against symbol `_ZTIN3nnp27SymmetryFunctionGroupRadialE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/nnp/lib/libnnp.a(SymmetryFunction.o): relocation R_X86_64_32 against `.rodata.str1.4' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:89: recipe for target '../lmp_serial' failed
make[1]: *** [../lmp_serial] Error 1
make[1]: Leaving directory '/home/hossein/lammps/src/Obj_serial'
Makefile:190: recipe for target 'serial' failed
make: *** [serial] Error 2

**Comment by singraber** [comment]
Hello!

Hmm.. unfortunately I can not reproduce the error: I compiled using Intel 18 and a fresh copy of n2p2 and LAMMPS (version `3 Mar 2020`) without any errors. It looks as if your LAMMPS build is trying to link the **dynamic** n2p2 libraries to the executable but the n2p2 lib files found are **static** versions. This may be connected to a recent change in the n2p2 makefiles, where the default switched from shared to static build. If you have set your LAMMPS to prefer dynamically linked libraries then you have to use the `MODE=shared` switch when compiling n2p2 (see [here](https://compphysvienna.github.io/n2p2/Topics/build.html#the-master-makefile)). On the other hand, if you use a fresh copy of both n2p2 and LAMMPS the default static build should work out of the box.

Maybe check the following:
- Did you really use a completely clean installation directory of both n2p2 (`make clean`) and LAMMPS(`make clean-all`)? In particular, make sure that you remove any remnants of the old n2p2 1.0.0 LAMMPS files, i.e. `lammps/src/pair_nnp.*` and `lammps/src/USER_NNP`, before copying `USER_NNP` from the new n2p2 and executing `make yes-user-nnp`.
- Double-check the `nnp` link in the `lammps/lib` directory.
- I recommend using the MPI version of LAMMPS.. if you intentionally decided to build the serial version you need to uncomment the line https://github.com/CompPhysVienna/n2p2/blob/c7b4407317fdf9bfcfd5a20f805f5e8948083243/src/makefile.intel#L44
which allows a non-MPI build of n2p2.
- Which are your compile flags in the LAMMPS makefile? For a serial build I use:
   ```
   CC =            icpc
   CCFLAGS =       -g -O3 -std=c++11 -ipo
   ...
   LINK =          icpc
   LINKFLAGS =     -g -O -std=c++11 -ipo
   ```
   and I would use `mpiicpc` instead of `icpc` for an MPI build.

Hope this helps, please report back...

Best,
Andi

**Comment by hghcomphys** [comment]
Hi, 

As you suggested, I re-made the n2p2 with `MODE=shared` and it resolved the problem.
I think the n2p2 dynamic vs. static linking was the issue when I noticed that default LAMMPS Makefile.mpi and Makefile.serial on my machine  (LAMMPs version 15 Apr 2020) is based on dynamic linking.

PS:
- I made n2p2 using `icc` while LAMMPS with `g++`  and there was no problem concerning the linking as well.
- `make serial` was also successfully done without any modification

Many thanks.

Best, 
Hossein
