### ISSUE TITLE
n2p2 in GPUs

### ISSUE THREAD

**Issue by E-4841** [CompPhysVienna/n2p2#43]
Hello, hope you're doing well.

Is it possible to use n2p2 on a GPU? I know that LAMMPS offers some packages that let GPUs build the neighbor lists. However, according to LAMMPS documentation when a non-GPU enabled command requires a neighbor list, the list will be built on the CPU. So I guess this won't work out with a neural network potential made with n2p2.

I was wondering if there are any other ways in which I can take advantage of a GPU when using n2p2. 

Thanks :)

**Comment by singraber** [comment]
Hello,

Unfortunately there is no direct GPU support in n2p2 at the moment. Also, even if the LAMMPS GPU neighbor lists could be used together with the CPU n2p2 library there would be no real benefit, since the most time-consuming part of the NNP is the computation of angular symmetry functions.

However, there is a recently developed implementation by a group at the Lawrence Livermore National Labratory (LLNL) for GPUs (via Kokkos) in [CabanaMD](https://github.com/ECP-copa/CabanaMD) (see also publication [here](https://arxiv.org/abs/2002.00054)), which is based on n2p2. I assume it uses similar input files and could be used with NNPs trained with n2p2 but I have not tried it yet, so please address any questions directly to the developers of CabanaMD.

Hope this helps a little bit!

**Comment by E-4841** [comment]
This is very helpful. 
Thank you!
