### ISSUE TITLE
Wrapping coordinates in n2p2

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#59]
Hi Andreas,
I am using CP2K for doing AIMD under PBC and data set construction. As you probably know, CP2K does not wrap the coordinates into the primary box, but works with the absolute coordinates. Now I want to know for creating the data set and the NNP training (under PBC), do I need to  wrap the coordinates into the box already or n2p2 will do that automatically and I can safely use the absolute and unwrapped coordinates? Many thanks.

**Comment by singraber** [comment]
Hey,

this should work since the atoms are remapped into the box automatically when the configurations are read, see here:

https://github.com/CompPhysVienna/n2p2/blob/af08e786cf243cf8b289f45ea8efcabeb2377c51/src/libnnp/Structure.cpp#L232-L239

and here:

https://github.com/CompPhysVienna/n2p2/blob/af08e786cf243cf8b289f45ea8efcabeb2377c51/src/libnnp/Structure.cpp#L434-L458

Anyway, better to check twice... you can try running `nnp-dist` which creates a radial distributions function (g(r)) for each element combination.. have a look whether this looks reasonable for your system.

If you continue on with `nnp-train` you could also have a look at the files `train.data` and `test.data` which should contain the remapped training and test data sets, respectively.

**Comment by moabe75** [comment]
Many thanks Andreas. I think checking the structures in the train.data and test.data files is the easiest way to make sure they have been already remapped. Great.

**Comment by singraber** [comment]
I am closing this... if you find that the remapping is not done as expected, please reopen!
