### ISSUE TITLE
Typos in Element.h ??!!

### ISSUE THREAD

**Issue by moabe75** [CompPhysVienna/n2p2#60]
Hi Andreas,

There is an error occurs in compiling LAMMPS NNP interface. I am not sure it's a bug, but wanted to report it to you. It complains about the ">>" in the Element.h file lines 156, 212, and 256 (https://github.com/CompPhysVienna/n2p2/blob/master/src/libnnp/Element.h) and says it should be "> >" (one space between them). When it's fixed it compiles successfully. 

Thanks.

**Comment by singraber** [comment]
Hey,

it is not a typo, just that `n2p2` depends on a C++ compiler with C++11 standard. As far as I remember since C++11 the space in between nested template brackets is not required any more. Just add the flag `-std=c++11` to your LAMMPS makefile and it should not complain any more.

Btw, the flags should be automatically handled with the new **automatic** LAMMPS build option:

https://compphysvienna.github.io/n2p2/Topics/if_lammps.html#automatic-build

**Comment by moabe75** [comment]
I see. Thanks for the explanation. 
I have not noticed there is an automatic LAMMPS build option. Next time I will use that.
