### ISSUE TITLE
Derivative of symmetries function

### ISSUE THREAD

**Issue by orielkiss** [CompPhysVienna/n2p2#68]
Dear n2p2 team,

I would like to know if there is a inbuild method to get acces to the derivatives of the symmetries functions. I would like to use n2p2 to compute symmetries function but i would also need their derivatives. I know that they are computed  at some point, because they are needed to compute the forces, but i would like to have access to them. They are called dGdr in the source code. 

What i would like is a file containg the derivative of each symmetries function with respect to each position. I guess they could be a optional keyword to call this feature.

Maybe this is already implemented and i missed it. In this case i would be really sorry for the disagrement. 

Thank you very much in advance
Best regards

Oriel

**Comment by singraber** [comment]
Hello Oriel,

depending on how you would like the data to be written out there are several ways to get the symmetry function derivatives in n2p2. However, as of now no provided tool does exactly what you want, so I am afraid a little bit of coding will be required. But before I start listing the options let me first clarify which quantities we are talking about: Let `G_i` be the vector of all symmetry functions which are calculated for atom `i`. Then, one needs to distinguish two derivatives, one are the derivatives with respect to the coordinates of the "central" atom i itself (`dG_i/dr_i`), and the other are w.r.t. coordinates of neighboring atoms (`dG_i/dr_j` , where `i != j`). Please have a look at the [supporting information](https://pubs.acs.org/doi/suppl/10.1021/acs.jctc.8b00770/suppl_file/ct8b00770_si_001.pdf) of [this paper](https://pubs.acs.org/doi/10.1021/acs.jctc.8b00770) for more insight.

Hence, in the implementation there is storage for both gradient "types", the first are saved in [`Atom::dGdr`](https://github.com/CompPhysVienna/n2p2/blob/67cbf5ae407ff464cbc6674ae93dec867e70a671/src/libnnp/Atom.h#L141), the latter are stored in [`Atom::Neighbor::dGdr`](https://github.com/CompPhysVienna/n2p2/blob/67cbf5ae407ff464cbc6674ae93dec867e70a671/src/libnnp/Atom.h#L64). In practice, as soon as the n2p2 setup finishes and the neighbor lists have been calculated for all atoms within a structure it is possible to call the function [`calculateSymmetryFunctionGroups(s, true)`](https://github.com/CompPhysVienna/n2p2/blob/67cbf5ae407ff464cbc6674ae93dec867e70a671/src/libnnp/Mode.h#L231), where `s` is an instance of the [`Structure`](https://github.com/CompPhysVienna/n2p2/blob/67cbf5ae407ff464cbc6674ae93dec867e70a671/src/libnnp/Structure.h#L32) class and the second argument determines if derivatives should be computed as well. After this function returns all the symmetry function values and derivatives have been stored in `s`. Here are some examples how you can access the data from C++ code:

- Get the first atom of structure `s`: `s.atoms[0]`
- Get a vector with all symmetry functions values of the first atom: `s.atoms[0].G`
- Get a vector with symmetry function derivatives of atom 0 w.r.t. its own coordinates: `s.atoms[0].dGdr` (returns a [`Vec3D`](https://github.com/CompPhysVienna/n2p2/blob/67cbf5ae407ff464cbc6674ae93dec867e70a671/src/libnnp/Vec3D.h#L28) object)
- Get the second neighbor of atom 0: `s.atoms[0].neighbors[1]` (Note that the neighbor index is not identical to the global atom index).
- Get atom index of second neighbor of atom 0: `s.atoms[0].neighbors[1].index`
- Get symmetry function derivatives of atom 0 w.r.t. coordinates of the second neighbor: `s.atoms[0].neighbors[1].dGdr (returns `Vec3D` object)

(A `Vec3D` object is a simple implementation of a three-dimensional vector, to access the underlying double-array just use the `.r` member, i.e. `dGdr.r`, which returns a `double[3]` C array).

I hope these examples help you understanding how the symmetry function data is organized in n2p2. This brings me to the options you have for putting it out on disk:

**1. Use the existing [`nnp-predict`](https://compphysvienna.github.io/n2p2/Tools/nnp-predict.html) tool:**

Go to the `examples/nnp-predict` directory and run one of the samples while enabling the debug output (provide `1` as argument). A pretty large file called `structure.out` will be created, which contains ALL data stored for the structure in `input.data`. It will contain sections like this:
```
********************************
ATOM
********************************
hasNeighborList                : 1
hasSymmetryFunctions           : 1
hasSymmetryFunctionDerivatives : 1
index                          : 0
indexStructure                 : 0
tag                            : 0
element                        : 0
numNeighbors                   : 59
numNeighborsUnique             : 60
numSymmetryFunctions           : 72
energy                         :  -4.37876255E-02
charge                         :   0.00000000E+00
r                              :   9.55381000E+00   9.85180000E-01   1.01838500E+01
f                              :  -1.40007861E-01   2.74032613E-02  -5.96150479E-03
fRef                           :  -1.25331000E-01   2.84150000E-02   3.11930000E-02

...

--------------------------------
dGdr                       [*] : 72
--------------------------------
                            0  :  -4.57964784E+42  -3.24427832E+43   3.70922432E+42
                            1  :   4.74905747E+46   8.35767350E+46  -4.29491607E+46
                            2  :  -8.64099236E+43  -6.37023512E+44   9.91855614E+43
                            3  :   3.46776690E+46   3.66106812E+46  -3.06006713E+46
                            4  :  -1.16779576E+45  -8.61591833E+45   1.87140131E+45
                            5  :  -7.49739585E+44  -5.49942737E+46   3.02360833E+46
                            6  :  -1.76825088E+46  -5.55808589E+46   4.35261388E+46
                            7  :  -6.16808325E+45  -9.47703018E+45   8.53514562E+45
                            8  :   9.83222755E+44  -2.57763225E+45   1.72192904E+45
                            9  :   2.28506346E+46   2.15463372E+46  -1.28634950E+46
```
and like this:
```
********************************
NEIGHBOR
********************************
index                          : 2
tag                            : 2
element                        : 0
d                              :   4.33579687E+00
rc                             :   6.00000000E+00
cutoffAlpha                    :   0.00000000E+00
fc                             :   1.34456178E-01
dfc                            :  -2.00870207E-01
cutoffType                     : 6
dr                             :   5.94337159E-01   1.97036000E+00  -3.81622580E+00
--------------------------------
dGdr                       [*] : 72
--------------------------------
                            0  :   4.14051373E-08   1.37267248E-07  -2.65861474E-07
                            1  :   0.00000000E+00   0.00000000E+00   0.00000000E+00
                            2  :   2.76146750E-06   9.15487955E-06  -1.77313219E-05
                            3  :   0.00000000E+00   0.00000000E+00   0.00000000E+00
                            4  :   1.36997459E-04   4.54177076E-04  -8.79657663E-04
                            5  :   0.00000000E+00   0.00000000E+00   0.00000000E+00
                            6  :   0.00000000E+00   0.00000000E+00   0.00000000E+00
```
which contain all the information you are interested in. However, this output is created for debugging purposes and may not be ideal for parsing and further processing.

**2. Play with derivatives in Python (use `pynnp`):**

n2p2 comes with a Cython interface to the C++ library, i.e. you can use (parts of) n2p2's functionality directly from Python. This comes in handy if one wants to play around with symmetry functions. Compile `pynnp` via `make pynnp` (needs Cython installed) and go to the "examples/pynnp/symfunc-only" directory. Run and examine either the [python script](https://github.com/CompPhysVienna/n2p2/blob/master/examples/pynnp/symfunc-only/example.py) or the Jupyter notebook there to see how you can work with the data. Note, that you need to set the second argument [here](https://github.com/CompPhysVienna/n2p2/blob/67cbf5ae407ff464cbc6674ae93dec867e70a671/examples/pynnp/symfunc-only/example.py#L38) to `True` in order to actually compute the derivatives. You can access the data in the same way as you would in C++, i.e. `s.atoms[0].dGdr`,...

**3. Write your own tool which efficiently computes derivatives and stores them on disk in the way you need it:**

If you need an MPI-parallelized program to quickly compute a lot of symmetry functions, do some processing and write stuff to disk I would suggest to copy and modify the existing `nnp-dataset` tool, which computes the NNP prediction for an entire data set of configurations. The basic program flow is probably similar to what you want but one can remove some code which is unnecessary for your purposes. If this is what you want, I can assist you and provide a "skeleton" program which you can then enhance on your own.

**VERY IMPORTANT:**

There are two important pieces of information in order to avoid confusion in either of the options I provided:

First, the symmetry functions you provide in the file "input.nn" are not used in the user-provided order but are rather sorted internally according to some criteria. Hence, the symmetry function arrays `Atom::G`, `Atom::dGdr` and `Atom::Neighbor::dGdr` are sorted in the same way. The sorted list of symmetry functions will be written out to screen and into the log file, just look out for this section:
```
*** SETUP: SYMMETRY FUNCTIONS *************************************************

Abbreviations:
--------------
ind .... Symmetry function index.
ec ..... Central atom element.
ty ..... Symmetry function type.
e1 ..... Neighbor 1 element.
e2 ..... Neighbor 2 element.
eta .... Gaussian width eta.
rs ..... Shift distance of Gaussian.
la ..... Angle prefactor lambda.
zeta ... Angle term exponent zeta.
rc ..... Cutoff radius.
ct ..... Cutoff type.
ca ..... Cutoff alpha.
ln ..... Line number in settings file.

Short range atomic symmetry functions element  S :
-------------------------------------------------------------------------------
 ind ec ty e1 e2       eta        rs la zeta        rc ct   ca    ln
-------------------------------------------------------------------------------
   1  S  2  S    2.000E+00 1.500E+00         6.000E+00  6 0.00    58
   2  S  2 Cu    2.000E+00 1.500E+00         6.000E+00  6 0.00    68
   3  S  2  S    2.000E+00 2.000E+00         6.000E+00  6 0.00    59
   4  S  2 Cu    2.000E+00 2.000E+00         6.000E+00  6 0.00    69
   5  S  2  S    2.000E+00 2.500E+00         6.000E+00  6 0.00    60
   6  S  2 Cu    2.000E+00 2.500E+00         6.000E+00  6 0.00    70
   7  S  2 Cu    2.000E+00 3.000E+00         6.000E+00  6 0.00    71
   8  S  3  S  S 1.653E-02 0.000E+00 -1  1.0 6.000E+00  6 0.00   116
...
```
Second, by default n2p2 is compiled with the flag [`-DIMPROVED_SFD_MEMORY`](https://compphysvienna.github.io/n2p2/Topics/build.html#improved-symmetry-function-derivative-memory) which avoids waste of symmetry function derivative memory in case of multi-element systems (see e.g. the lines starting with 1,3,5,6 in the above example of `NEIGHBOR`'s `dGdr` which contain only zeros). While this is useful in general to save a substantial amount of memory (e.g. during NNP training) it will be very obstructive for your purposes because you loose the one-to-one correspondence of the `dGdr`array with the list of sorted symmetry functions. Therefore, in your case I strongly recommend to always compile the code without this feature, i.e. disable it by commenting out the option in the makefile.<compiler> you are using, e.g. here:

https://github.com/CompPhysVienna/n2p2/blob/67cbf5ae407ff464cbc6674ae93dec867e70a671/src/makefile.gnu#L58

Alright... I am afraid this is a lot to digest for the moment but I hope it gives you a good start... keep asking if anything is unclear (and in particular if you choose to follow path (3))!

Best,

Andreas

**Comment by orielkiss** [comment]
Dear Andreas,

Thank you for your prompt and very clear answer, I really appreciate it. It definitely helps a lot. I will go for option 1 since my C++ is not so good and I only need the derivatives for few small data sets. Then it will be relatively short to get the derivatives from the structure file.
Thanks you very much for your time and for this amazing work.

Best 
Oriel
