### ISSUE TITLE
Energy/force update counts change with MPI processes used

### ISSUE THREAD

**Issue by xyttyxy** [CompPhysVienna/n2p2#93]
**The question**
The update counting printed in training loop count to stdout changes with MPI processes?

**What did you already try?**
when I ran 'mpirun -np <number_of_processes> nnp-train', the resulting energy/force updates printed out roughly changes with with the number of processes I used:

With 8 cores: 

```
-------------------------------------------------------------------
ENERGY      0        0   1.57377E-01   1.42365E-01     0.0
FORCE       0        0   1.08320E+00   1.07449E+00     0.0
TIMING      0        0    0.0   99.1    0.9       3.30       3.30
------
ENERGY      1      145   1.74575E-02   1.83459E-02     7.2
FORCE       1      512   8.33865E-01   7.96215E-01    92.8
TIMING      1      657   97.6    2.2    0.2      16.37      19.67
------
ENERGY      2      145   1.74838E-02   1.80318E-02     7.4
FORCE       2      512   8.56411E-01   8.43148E-01    92.5
TIMING      2      657   97.6    2.2    0.2      16.34      36.01
------

```
With 32 cores: 
```
-------------------------------------------------------------------
ENERGY      0        0   1.47778E-01   1.44476E-01     0.0
FORCE       0        0   1.10788E+00   1.10737E+00     0.0
TIMING      0        0    0.0   96.9    3.1       0.97       0.97
------
ENERGY      1       36   1.44452E-02   1.66778E-02    18.8
FORCE       1      127   8.35029E-01   8.21357E-01    81.2
TIMING      1      163   98.7    1.1    0.1      18.86      19.83
------
ENERGY      2       36   1.35292E-02   1.56059E-02    19.2
FORCE       2      127   8.00855E-01   7.89173E-01    80.8
TIMING      2      163   98.7    1.1    0.2      18.50      38.33

```
With 64 cores: 
```
-------------------------------------------------------------------
ENERGY      0        0   1.30789E-01   1.44305E-01     0.0
FORCE       0        0   1.10898E+00   1.09058E+00     0.0
TIMING      0        0    0.0   95.4    4.6       0.65       0.65
------
ENERGY      1       18   1.54163E-02   1.59892E-02    18.9
FORCE       1       63   8.57907E-01   8.58333E-01    81.1
TIMING      1       81   97.4    2.3    0.3      10.80      11.45
------
ENERGY      2       18   1.47786E-02   1.72260E-02    18.2
FORCE       2       63   7.84609E-01   1.37909E+00    81.8
TIMING      2       81   97.6    2.1    0.3      11.05      22.50
-------------------------------------------------------------------

```
I'm not sure if this was the intended behavior. 

**Background**
This was on SDSC Expanse cluster. Program was compiled with gcc 10.2.0 + openmpi 4.0.4

**Comment by singraber** [comment]
Hi!

This is the expected behavior, please have a look at the corresponding [publication](https://doi.org/10.1021/acs.jctc.8b01092). In short words:

An epoch is defined by using each training pattern available in the data set one time (on average, this can be modified by keywords `short_energy_fraction` and `short_force_fraction`). In a serial run the number of weight updates equals to the number of training patterns (energies/forces). However, the multi-stream Kalman filter training implemented in *n2p2* allows us to use multiple training patterns in a single weight update step. If you run *n2p2* training in parallel each process contributes one training pattern to such a combined weight update. Hence, in order to keep the total amount of information used for one epoch fixed, the number of weight updates is reduced accordingly. In your example, if you start with 145 energy updates on 8 cores the number of updates on 32 cores is 36, which is roughly 145/4. At the same time the number of energies used per update increases, please check the output which should say something like `Patterns used per update ...`

**Comment by xyttyxy** [comment]
Thanks for the prompt response! That makes perfect sense. 

I suppose it also explains the parallel scaling performance I was observing. The scaling was almost perfect (double cores, half per-epoch CPU time) up until 64 cores. More than 64 I see sudden degradation.

**Comment by singraber** [comment]
Yes, that's mostly the reason for the parallel performance.. I would not recommend to go much higher than 48 cores anyway because it seems that the fitting results with the multi-stream Kalman filter method become worse. There seems to be a sweet spot at around 16~32 cores (see also the publication)... of course this might be system-dependent.
